import Search from "@/components/dashboard/search";
import { BASE_URL, PAGES } from "@/constants/constants";
import { Metadata } from "next";

export const generateMetadata = (): Metadata => {
  return {
    title: `Search ~ Willow`,
    description: "Generated by create next app", // Fix this
    openGraph: {
      title: `Search ~ Willow`,
      description: "Generated by create next app", // Fix this
      type: "website",
      url: BASE_URL + PAGES.dashboard.search(),
      images: [
        {
          url: "", // Fix this
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: `Search ~ Willow`,
      description: "Generated by create next app",
      images: [
        {
          url: "", // Fix this
        },
      ],
    },
  };
};

const Page = async () => {
  return <Search />;
};

export default Page;
