import Login from "@/components/auth/login";
import { BASE_URL, PAGES } from "@/constants/constants";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login ~ Willow",
  description: "Generated by create next app", // Fix this
  openGraph: {
    title: "Login ~ Willow",
    description: "Generated by create next app", // Fix this
    type: "website",
    url: BASE_URL + PAGES.auth.login,

    images: [
      {
        url: "", // Fix this
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Login ~ Willow",
    description: "Generated by create next app",

    images: [
      {
        url: "", // Fix this
      },
    ],
  },
};

const LoginPage = () => {
  return <Login />;
};

export default LoginPage;
