"use client";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import Link from "next/link";
import { PAGES } from "@/constants/constants";
import { FormEvent, useRef, useState } from "react";
import { Checkbox } from "@/components/ui/checkbox";

// export const metadata: Metadata = {
//   title: "Login ~ Willow",
//   description: "Generated by create next app",
// };

// USE THE GENERATE METADATA FUNCTION TO GET THE METADATA

const LoginPage = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);

  const login = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    alert(`${email} ${password}`);
  };

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-col items-center gap-2 text-center">
        <h1 className="text-2xl font-semibold">Login to your account</h1>
        <p className="text-balance text-sm text-muted-foreground">
          Enter your details below to login to your account
        </p>
      </div>

      <div className="grid gap-6">
        <div className="grid gap-2">
          <Label htmlFor="email">Email</Label>
          <Input
            id="email"
            type="email"
            placeholder="m@example.com"
            required
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
        </div>

        <div className="grid gap-2">
          <div className="flex items-center">
            <Label htmlFor="password">Password</Label>
            <Link
              href={PAGES.auth.forgot_password}
              className="ml-auto text-sm underline-offset-4 hover:underline"
            >
              Forgot your password?
            </Link>
          </div>
          <Input
            id="password"
            type={showPassword ? "text" : "password"}
            required
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            placeholder="••••••••"
          />
        </div>

        <div className="flex items-center space-x-2">
          <Checkbox
            id="show-password"
            checked={showPassword}
            onClick={() => setShowPassword((k) => !k)}
          />
          <Label htmlFor="show-password">Show password</Label>
        </div>

        <Button className="w-full bg-main hover:bg-main/90" type="submit">
          Login
        </Button>
      </div>

      <div className="text-center text-sm">
        Don&apos;t have an account?{" "}
        <Link
          href={PAGES.auth.register}
          className="underline underline-offset-4 text-main"
        >
          Sign up
        </Link>
      </div>
    </div>
  );
};

export default LoginPage;
