"use client";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import Link from "next/link";
import { PAGES } from "@/constants/constants";
import { FormEvent, useRef } from "react";

// export const metadata: Metadata = {
//   title: "Login ~ Willow",
//   description: "Generated by create next app",
// };

// USE THE GENERATE METADATA FUNCTION TO GET THE METADATA

const LoginPage = () => {
  const emailRef = useRef<HTMLInputElement>(null);
  const passwordRef = useRef<HTMLInputElement>(null);

  const login = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    const email = emailRef.current?.value;
    const password = passwordRef.current?.value;

    alert(`${email} ${password}`);
  };

  return (
    <form className="flex flex-col gap-6" onSubmit={login}>
      <div className="flex flex-col items-center gap-2 text-center">
        <h1 className="text-2xl font-semibold">Login to your account</h1>
        <p className="text-balance text-sm text-muted-foreground">
          Enter your email below to login to your account
        </p>
      </div>

      <div className="grid gap-6">
        <div className="grid gap-2">
          <Label htmlFor="email">Email</Label>
          <Input
            id="email"
            type="email"
            placeholder="m@example.com"
            required
            ref={emailRef}
          />
        </div>

        <div className="grid gap-2">
          <div className="flex items-center">
            <Label htmlFor="password">Password</Label>
            <Link
              href={PAGES.auth.forgot_password}
              className="ml-auto text-sm underline-offset-4 hover:underline"
            >
              Forgot your password?
            </Link>
          </div>
          <Input id="password" type="password" required ref={passwordRef} />
        </div>

        <Button className="w-full bg-main hover:bg-main/90" type="submit">
          Login
        </Button>
      </div>

      <div className="text-center text-sm">
        Don&apos;t have an account?{" "}
        <Link
          href={PAGES.auth.register}
          className="underline underline-offset-4 text-main"
        >
          Sign up
        </Link>
      </div>
    </form>
  );
};

export default LoginPage;
