import ResetPassword from "@/components/auth/reset-password";
import { BASE_URL, PAGES } from "@/constants/constants";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Reset password ~ Willow",
  description: "Generated by create next app", // Fix this
  openGraph: {
    title: "Reset password ~ Willow",
    description: "Generated by create next app", // Fix this
    type: "website",
    url: BASE_URL + PAGES.auth.reset_password,
    images: [
      {
        url: "", // Fix this
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Reset password ~ Willow",
    description: "Generated by create next app",

    images: [
      {
        url: "", // Fix this
      },
    ],
  },
};

const LoginPage = () => {
  return <ResetPassword />;
};

export default LoginPage;
