"use client";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import Link from "next/link";
import { PAGES } from "@/constants/constants";
import { useEffect, useState } from "react";
import { cn, validateInputs, validatePassword } from "@/lib/utils";
import { Checkbox } from "@/components/ui/checkbox";
import { ArrowLeft } from "lucide-react";
import toast from "react-hot-toast";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";

// export const metadata: Metadata = {
//   title: "Login ~ Willow",
//   description: "Generated by create next app",
// };

// USE THE GENERATE METADATA FUNCTION TO GET THE METADATA

const RegisterPage = () => {
  const [stage, setStage] = useState(1);
  const [description, setDescription] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [fullName, setFullName] = useState("");
  const [showPassword, setShowPassword] = useState(false);

  // const register = (e: FormEvent<HTMLFormElement>) => {
  //   e.preventDefault();

  //   alert(`${email} ${password} ${fullName}`);
  // };

  const validateAndUpdateStage = (next: number) => {
    const isEmail = validateInputs("email", email);
    const isFullName = validateInputs("name", fullName);
    const isPassword = validatePassword(password);

    if (next === 2) {
      if (isEmail && isFullName) setStage(next);
      else toast.error("Please enter a valid email and name.");
    } else if (next === 3) {
      if (isPassword.valid) setStage(next);
      else toast.error(isPassword.reason);
    }
  };

  useEffect(() => {
    if (stage === 1)
      setDescription("Enter your email and full name to get started");
    else if (stage === 2)
      setDescription("Enter your password to continue the registration");
    else if (stage === 3)
      setDescription("Add a profile picture to personalize your experience");
  }, [stage]);

  return (
    <div className="flex flex-col gap-6">
      <Button
        className="w-fit cursor-pointer"
        variant="ghost"
        onClick={() => stage !== 1 && setStage((k) => k - 1)}
      >
        <ArrowLeft /> Back
      </Button>

      <div className="flex flex-col items-center gap-2 text-center">
        <h1 className="text-2xl font-semibold">Welcome to Willow</h1>
        <p className="text-balance text-sm text-muted-foreground">
          {description}
        </p>
      </div>

      <p className="w-full text-center text-muted-foreground text-sm font-medium">
        STEP {stage} OF 3
      </p>

      <div className={cn("gap-6", stage === 1 ? "grid" : "hidden")}>
        <div className="grid gap-2">
          <Label htmlFor="email">Email</Label>
          <Input
            id="email"
            type="email"
            placeholder="m@example.com"
            required
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
        </div>

        <div className="grid gap-2">
          <Label htmlFor="full-name">Full name</Label>
          <Input
            id="full-name"
            type="text"
            placeholder="John Doe"
            required
            value={fullName}
            onChange={(e) => setFullName(e.target.value)}
          />
        </div>

        <Button
          className="w-full bg-main hover:bg-main/90 cursor-pointer"
          onClick={() => validateAndUpdateStage(2)}
        >
          Continue
        </Button>
      </div>

      <div className={cn("gap-6", stage === 2 ? "grid" : "hidden")}>
        <div className="grid gap-2">
          <Label htmlFor="password">Password</Label>
          <Input
            id="password"
            type={showPassword ? "text" : "password"}
            required
            placeholder="••••••••"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
        </div>

        <div className="flex items-center space-x-2">
          <Checkbox
            id="show-password"
            checked={showPassword}
            onClick={() => setShowPassword((k) => !k)}
          />
          <Label htmlFor="show-password">Show password</Label>
        </div>

        <Button
          className="w-full bg-main hover:bg-main/90 cursor-pointer"
          onClick={() => validateAndUpdateStage(3)}
        >
          Continue
        </Button>
      </div>

      <div className={cn("gap-6", stage === 3 ? "grid" : "hidden")}>
        <Avatar className="w-24 h-24 self-center justify-self-center">
          <AvatarImage
            src={`https://api.dicebear.com/9.x/notionists-neutral/svg?seed=${email}`}
            className="border-2 border-main rounded-full"
          />
          <AvatarFallback>WLOW</AvatarFallback>
        </Avatar>

        <div className="relative inline-block w-full">
          <Button
            className="w-full text-main bg-main/10 cursor-pointer"
            variant="ghost"
            onClick={() => validateAndUpdateStage(3)}
          >
            Upload profile picture
          </Button>

          <Input
            type="file"
            id="file-upload"
            accept="image/*"
            className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
          />
        </div>

        <Button className="w-full bg-main hover:bg-main/90" type="submit">
          Finish with default
        </Button>
      </div>

      <div className="text-center text-sm">
        Already have an account?{" "}
        <Link
          href={PAGES.auth.login}
          className="underline underline-offset-4 text-main"
        >
          Login
        </Link>
      </div>
    </div>
  );
};

export default RegisterPage;
