import Product from "@/components/general/product";
import { BASE_URL, PAGES } from "@/constants/constants";
import { getProduct } from "@/lib/requests/general";
import { Metadata } from "next";

export const generateMetadata = async (props: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> => {
  const { id } = await props.params;

  return {
    // work on this
    title: "Product ~ Willow",
    description: "Generated by create next app",
    openGraph: {
      title: "Product ~ Willow",
      description: "Generated by create next app",
      type: "website",
      url: BASE_URL + PAGES.main.shop.product(id),
      images: [
        {
          url: "", // Fix this
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: "Product ~ Willow",
      description: "Generated by create next app",
      images: [
        {
          url: "", // Fix this
        },
      ],
    },
  };
};

const Page = async (props: { params: Promise<{ id: string }> }) => {
  const { id } = await props.params;

  return <Product productId={id} />;
};

export default Page;
