import Product from "@/components/general/product";
import { BASE_URL, PAGES } from "@/constants/constants";
import { Metadata } from "next";

export const generateMetadata = async (props: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> => {
  const params = await props.params;

  return {
    // work on this
    title: "Pblafdkljroducts ~ Willow",
    description: "Generated by create next app", // Fix this
    openGraph: {
      title: "Products ~ Willow",
      description: "Generated by create next app", // Fix this
      type: "website",
      url: BASE_URL + PAGES.main.shop.product(params.id),
      images: [
        {
          url: "", // Fix this
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: "Products ~ Willow",
      description: "Generated by create next app",
      images: [
        {
          url: "", // Fix this
        },
      ],
    },
  };
};

const Page = async (props: { params: Promise<{ id: string }> }) => {
  const params = await props.params;
  console.log(params);

  return <Product />;
};

export default Page;
