import Product from "@/components/general/product";
import Cart from "@/components/main/cart";
import Order from "@/components/main/order";
import { BASE_URL, PAGES } from "@/constants/constants";
import { Metadata } from "next";

export const metadata: Metadata = {
  // work on this
  title: "Your cart ~ Willow",
  description: "Generated by create next app", // Fix this
  openGraph: {
    title: "Your cart ~ Willow",
    description: "Generated by create next app", // Fix this
    type: "website",
    url: BASE_URL + PAGES.main.shop.cart,
    images: [
      {
        url: "", // Fix this
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Your cart ~ Willow",
    description: "Generated by create next app",
    images: [
      {
        url: "", // Fix this
      },
    ],
  },
};

const Page = async () => {
  return <Cart />;
};

export default Page;
