import Seller from "@/components/main/seller";
import { BASE_URL, PAGES } from "@/constants/constants";
import { getSellerDetails } from "@/lib/requests/seller";
import { Metadata } from "next";

export const generateMetadata = async (props: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> => {
  const { id } = await props.params;

  const { data, error } = await getSellerDetails(id);

  if (error) {
    return {
      title: "Willow",
      description: "Generated by create next app", // Fix this
      openGraph: {
        title: "Willow",
        description: "Generated by create next app", // Fix this
        type: "website",
        url: BASE_URL + PAGES.main.shop.seller(id),
        images: [
          {
            url: "", // Fix this
          },
        ],
      },
      twitter: {
        card: "summary_large_image",
        title: "Willow",
        description: "Generated by create next app",
        images: [
          {
            url: "", // Fix this
          },
        ],
      },
    };
  }

  return {
    // work on this
    title: `${data?.user.businessName} ~ Willow`,
    description: data?.user.bio,
    openGraph: {
      title: `${data?.user.businessName} ~ Willow`,
      description: data?.user.bio,
      type: "website",
      url: BASE_URL + PAGES.main.shop.seller(id),
      images: [
        {
          url: "", // Fix this
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: `${data?.user.businessName} ~ Willow`,
      description: data?.user.bio,
      images: [
        {
          url: "", // Fix this
        },
      ],
    },
  };
};

const Page = async (props: { params: Promise<{ id: string }> }) => {
  const { id } = await props.params;

  return <Seller id={id} />;
};

export default Page;
