import Search from "@/components/main/search";
import { BASE_URL, PAGES } from "@/constants/constants";
import { Metadata } from "next";

export const generateMetadata = async (props: {
  params: Promise<{ term: string }>;
}): Promise<Metadata> => {
  const { term } = await props.params;

  return {
    title: `Search: ${term} ~ Willow`,
    description: "Generated by create next app", // Fix this
    openGraph: {
      title: `Search: ${term} ~ Willow`,
      description: "Generated by create next app", // Fix this
      type: "website",
      url: BASE_URL + PAGES.main.shop.search(term),
      images: [
        {
          url: "", // Fix this
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: `Search: ${term} ~ Willow`,
      description: "Generated by create next app",
      images: [
        {
          url: "", // Fix this
        },
      ],
    },
  };
};

const Page = async (props: { params: Promise<{ term: string }> }) => {
  const params = await props.params;
  console.log(params);

  return <Search />;
};

export default Page;
