import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import { Toaster } from "react-hot-toast";
import { Toaster as Sonner } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className="antialiased flex items-center justify-center bg-[#f5f5f5]">
        <Toaster />
        <Sonner />
        <Suspense>{children}</Suspense>
      </body>
    </html>
  );
};

export default RootLayout;
