import Register from "@/components/auth/register";
import { BASE_URL, PAGES } from "@/constants/constants";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Register ~ Willow",
  description: "Generated by create next app", // Fix this
  openGraph: {
    title: "Register ~ Willow",
    description: "Generated by create next app", // Fix this
    type: "website",
    url: BASE_URL + PAGES.auth.register,
    images: [
      {
        url: "", // Fix this
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Register ~ Willow",
    description: "Generated by create next app",

    images: [
      {
        url: "", // Fix this
      },
    ],
  },
};

const RegisterPage = () => {
  return <Register />;
};

export default RegisterPage;
