import Header from "@/components/main/header";
import ImageCarousel from "@/components/main/image-carousel";
import { BASE_URL, IMAGES, PAGES } from "@/constants/constants";
import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "More about Willow",
  description: "Generated by create next app", // Fix this
  openGraph: {
    title: "More about Willow",
    description: "Generated by create next app", // Fix this
    type: "website",
    url: BASE_URL + PAGES.main.more_about_willow,
    images: [
      {
        url: "", // Fix this
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "More about Willow",
    description: "Generated by create next app",

    images: [
      {
        url: "", // Fix this
      },
    ],
  },
};

const Page = () => {
  return (
    <>
      <h1 className="text-xl md:text-2xl font-semibold">
        Our Sustainability Approach
      </h1>

      <div className="w-full flex flex-col md:flex-row gap-6">
        <div className="w-full md:w-5/12">
          <div className="bg-white shadow border rounded-lg p-4 flex flex-col items-center justify-center gap-6">
            <p className="text-center lg:text-lg">
              “Do not wait for extraordinary situations to do good action; try
              to use ordinary situations.”
            </p>

            <p className="text-sm text-gray-400">Jean-Paul Ritcher</p>
          </div>

          <p className="mt-6">
            At Willow, we believe that being eco-friendly means embracing
            complexity—not settling for one-size-fits-all solutions. We know
            that no product or process is perfectly sustainable, and complete
            sustainability is an ideal rather than an absolute. That&apos;s why
            we carefully weigh every option against our sustainability criteria
            and simplify your experience by highlighting clear sustainability
            tags on every listed product.
          </p>
        </div>

        <div className="w-full md:w-7/12 rounded-xl overflow-hidden aspect-video">
          <Image
            src={IMAGES.more_about_willow.one.src}
            width={IMAGES.more_about_willow.one.w}
            height={IMAGES.more_about_willow.one.h}
            alt="Image one"
            className="w-full h-full object-cover"
          />
        </div>
      </div>

      <hr />

      <div className="w-full flex flex-col lg:flex-row gap-6">
        <div className="w-full lg:w-7/12 flex flex-col gap-6">
          <h3 className="text-lg lg:text-xl font-semibold">
            Balancing Emissions and Long-Term Impact
          </h3>

          <p>
            <span className="font-semibold">Lowering Emissions:</span>
            <br /> We partner with sellers who use innovative production methods
            to reduce greenhouse gas emissions. For instance, products made from
            recycled polyester (rPET) repurpose waste, cutting down on the
            energy required to produce new materials.
          </p>

          <p>
            <span className="font-semibold">Thinking Ahead:</span>
            <br /> While lower emissions are critical, we recognize that every
            approach has its trade-offs. Synthetic materials like rPET may shed
            microplastics, and even natural, biodegradable products can demand
            higher resource inputs during production. We approve both approaches
            through our rigorous vetting process—because often, no single
            solution can achieve complete sustainability.
          </p>

          <h3 className="text-lg lg:text-xl font-semibold">
            Credibility Through AI-assisted Vetting
          </h3>

          <p>
            <span className="font-semibold">Earning Your Trust:</span>
            <br /> Every seller on Willow undergoes a stringent evaluation
            process, regardless of whether they provide official certifications.
            Sellers who present verified documentation—such as Fair Trade,
            Organic, or Carbon Neutral certificates—gain an extra layer of
            credibility. However, even if a seller doesn&apos;t have formal
            certification, they&apos;re held to the same high standards,
            ensuring that every eco-friendly claim on our site is reliable and
            thoroughly vetted.
          </p>

          <h3 className="text-lg lg:text-xl font-semibold">
            Flexible Options, Consistent Standards
          </h3>

          <p>
            <span className="font-semibold">Custom Choices:</span>
            <br /> Depending on the category, products on our platform feature
            detailed options like sizes, colors, and materials. This flexibility
            lets you find the perfect match for your lifestyle.
          </p>

          <p>
            <span className="font-semibold">Clear Eco-Attributes:</span>
            <br /> For key sustainability aspects—such as packaging and
            eco-friendly practices—we offer standardized selections. This means
            when you see tags like “minimal carbon footprint” or “energy
            efficient,” you know exactly what they represent.
          </p>

          <h3 className="text-lg lg:text-xl font-semibold">
            Value Beyond Price
          </h3>

          <p>
            Eco-friendly products can sometimes come with a higher price tag due
            to ethical sourcing and sustainable production practices. By
            providing detailed sustainability metrics and transparent product
            information, we help you see the true value behind every
            eco-friendly item—even if it costs a bit more.
          </p>

          <h3 className="text-lg lg:text-xl font-semibold">
            A Multifaceted Commitment
          </h3>

          <p>
            Sustainability isn&apos;t one-dimensional. Some products excel at
            reducing emissions, while others shine in their long-term
            environmental impact. Our platform is designed to showcase a broad
            range of eco-features, empowering you to make choices that best
            align with your values.
          </p>
        </div>

        <div className="w-full lg:w-5/12 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-1 gap-6 self-start">
          <div className="bg-white shadow border rounded-lg p-4 flex flex-col items-center justify-center gap-6">
            <p className="text-center lg:text-lg">
              “If it can&apos;t be reduced, reused, repaired, rebuilt,
              refurbished, refinished, resold, recycled, or composted, then it
              should be restricted, redesigned, or removed from production.”
            </p>

            <p className="text-sm text-gray-400">Pete Seeger</p>
          </div>

          <div className="bg-white shadow border rounded-lg p-4 flex flex-col items-center justify-center gap-6">
            <p className="text-center lg:text-lg">
              “We have the power to change the narrative. Let&apos;s rewrite the
              story of our planet and ensure that it&apos;s a tale of
              resilience, sustainability, and hope.”
            </p>

            <p className="text-sm text-gray-400">Jamie Margolin</p>
          </div>

          <div className="bg-white shadow border rounded-lg p-4 flex flex-col items-center justify-center gap-6">
            <p className="text-center lg:text-lg">
              “Climate change is the single greatest threat to a sustainable
              future but, at the same time, addressing the climate challenge
              presents a golden opportunity to promote prosperity, security and
              a brighter future for all.”
            </p>

            <p className="text-sm text-gray-400">Ban Ki-moon</p>
          </div>

          <div className="bg-white shadow border rounded-lg p-4 flex flex-col items-center justify-center gap-6">
            <p className="text-center lg:text-lg">
              “You cannot protect the environment unless you empower people, you
              inform them, and you help them understand that these resources are
              their own, that they must protect them.”
            </p>

            <p className="text-sm text-gray-400">
              Wangari Maathai, political activist
            </p>
          </div>
        </div>
      </div>

      <ImageCarousel />

      <p className="w-full">
        At Willow, we&apos;re not just curating eco-friendly products—we&apos;re
        pioneering a movement towards conscious consumption. While we recognize
        that no single solution is perfect, our commitment to rigorous,
        transparent vetting means that every sustainability tag represents a
        genuine effort to balance environmental impact with practicality. We
        invite you to explore our collection, learn about the green initiatives
        behind each product, and join a community dedicated to making smarter,
        more responsible choices for our planet. Together, we can drive
        meaningful change toward a greener future.
      </p>
    </>
  );
};

export default Page;
