import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { BASE_URL, PAGES } from "@/constants/constants";
import { Heart, Leaf, ShoppingBasket } from "lucide-react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Wishlist ~ Willow",
  description: "Generated by create next app", // Fix this
  openGraph: {
    title: "Wishlist ~ Willow",
    description: "Generated by create next app", // Fix this
    type: "website",
    url: BASE_URL + PAGES.main.shop.wishlist,
    images: [
      {
        url: "", // Fix this
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Wishlist ~ Willow",
    description: "Generated by create next app",
    images: [
      {
        url: "", // Fix this
      },
    ],
  },
};

const Page = () => {
  return (
    <>
      <h5 className="text-lg md:text-xl font-medium">Wishlist (10)</h5>

      <Separator />

      <div className="w-full grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-4">
        <div className="bg-white p-2 rounded-lg border shadow flex flex-col gap-2 relative">
          <div className="w-full flex items-center justify-between">
            <div className="text-main border px-2 py-1 flex items-center justify-center text-xs gap-1 rounded-md font-medium w-fit">
              <Leaf size={14} /> Biodegradable
            </div>

            <Heart size={18} />
          </div>

          <div className="overflow-hidden aspect-square rounded-md">
            <img
              src="https://github.com/victoribironke.png"
              alt="Image"
              className="w-full h-full object-cover"
            />
          </div>

          <p className="font-medium">Pine Scent Body Rub</p>

          <p className="text-sm text-[#696969]">Cosmetics</p>

          <p className="text-sm font-medium">₦ 23,500</p>

          <Button className="text-white hover:bg-main/90 h-auto bg-main w-fit absolute bottom-2 right-2">
            <ShoppingBasket size={20} />
          </Button>
        </div>
      </div>
    </>
  );
};

export default Page;
