import ForgotPassword from "@/components/auth/forgot-password";
import { BASE_URL, PAGES } from "@/constants/constants";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Forgot password ~ Willow",
  description: "Generated by create next app", // Fix this
  openGraph: {
    title: "Forgot password ~ Willow",
    description: "Generated by create next app", // Fix this
    type: "website",
    url: BASE_URL + PAGES.auth.forgot_password,
    images: [
      {
        url: "", // Fix this
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Forgot password ~ Willow",
    description: "Generated by create next app",

    images: [
      {
        url: "", // Fix this
      },
    ],
  },
};

const ForgotPasswordPage = () => {
  return <ForgotPassword />;
};

export default ForgotPasswordPage;
