"use client";

// import type { Metadata } from "next";
import PageLoader from "@/components/general/page-loader";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import Link from "next/link";
import { PAGES, SIDEBAR_ITEMS } from "@/constants/constants";
import { Button } from "@/components/ui/button";
import { cn, getJwtExpiration } from "@/lib/utils";
import { usePathname } from "next/navigation";
import Logo from "@/components/general/logo";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
// import { Input } from "@/components/ui/input";
import { useRouter } from "next/navigation";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { logOut } from "@/lib/auth";
import { Menu } from "lucide-react";

// export const metadata: Metadata = {
//   title: "Home ~ Willow",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      refetchInterval: 10000,
    },
  },
});

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const [loading, setLoading] = useState(true);
  const { push } = useRouter();
  const pathname = usePathname();

  useEffect(() => {
    const data = localStorage.getItem("willow_auth_data");

    if (!data) {
      push(PAGES.auth.login);
      return;
    }

    if (JSON.parse(data).role !== "SELLER") {
      push(PAGES.main.shop.profile);
      return;
    }

    const { access_token } = JSON.parse(data);

    const date_ms = new Date().getTime();
    const expires_at = getJwtExpiration(access_token);

    if (!expires_at || date_ms >= expires_at) {
      localStorage.removeItem("willow_auth_data");
      push(PAGES.auth.login);
      return;
    }

    setLoading(false);
  }, [push]);

  if (loading) return <PageLoader fullScreen />;

  return (
    <QueryClientProvider client={queryClient}>
      <div className="w-full [--header-height:calc(theme(spacing.14))] bg-[#f5f5f5]">
        <section className="w-full min-h-screen flex items-center flex-col relative pt-16">
          <div className="w-full bg-white border-b p-4 flex items-center justify-center fixed z-50 top-0">
            <div className="w-full max-w-[1280px] flex gap-4 items-center justify-between">
              <DropdownMenu>
                <DropdownMenuTrigger className="md:hidden">
                  <Menu />
                </DropdownMenuTrigger>
                <DropdownMenuContent className="mx-4 md:hidden">
                  {SIDEBAR_ITEMS(pathname).map((s, i) => (
                    <DropdownMenuItem key={i}>
                      <Link href={s.link} key={i} className="w-full">
                        <Button
                          className={cn(
                            "w-full justify-start hover:bg-gray-200 gap-2 px-3",
                            s.isActive ? "bg-main/10 hover:bg-main/10" : ""
                          )}
                          variant="ghost"
                        >
                          <s.icon />
                          {s.title}
                        </Button>
                      </Link>
                    </DropdownMenuItem>
                  ))}
                </DropdownMenuContent>
              </DropdownMenu>

              <Logo />

              {/* <div className="w-full max-w-md">
                    <Input
                      className="w-full rounded-full"
                      placeholder="Search products"
                    />
                  </div> */}

              <DropdownMenu>
                <DropdownMenuTrigger>
                  <Avatar className="h-8 w-8 rounded-full">
                    <AvatarImage
                      src="https://github.com/victoribironke.png"
                      alt={"user.name"}
                    />
                    <AvatarFallback className="rounded-lg">CN</AvatarFallback>
                  </Avatar>
                </DropdownMenuTrigger>
                <DropdownMenuContent className="mx-4">
                  <DropdownMenuLabel>My Account</DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem onClick={logOut}>Log out</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>

          <div className="w-full bg-gray-100 min-h-[calc(100vh-4rem)] p-4 pb-10 flex items-center flex-col">
            <div className="w-full flex gap-8 max-w-[1280px] h-auto relative">
              <div className="w-80 hidden md:flex flex-col gap-2 sticky top-20 h-full">
                {SIDEBAR_ITEMS(pathname).map((s, i) => (
                  <Link href={s.link} key={i}>
                    <Button
                      className={cn(
                        "w-full justify-start hover:bg-gray-200 gap-4 text-base",
                        s.isActive ? "bg-main/10 hover:bg-main/10" : ""
                      )}
                      variant="ghost"
                    >
                      <s.icon />
                      {s.title}
                    </Button>
                  </Link>
                ))}
              </div>

              <div className="w-full flex flex-col gap-6">{children}</div>
            </div>
          </div>
        </section>
      </div>
    </QueryClientProvider>
  );
};

export default RootLayout;
