import Chats from "@/components/main/chats";
import { BASE_URL, PAGES } from "@/constants/constants";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Chats ~ Willow",
  description: "Generated by create next app", // Fix this
  openGraph: {
    title: "Chats ~ Willow",
    description: "Generated by create next app", // Fix this
    type: "website",
    url: BASE_URL + PAGES.main.shop.chats,
    images: [
      {
        url: "", // Fix this
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Chats ~ Willow",
    description: "Generated by create next app",
    images: [
      {
        url: "", // Fix this
      },
    ],
  },
};

const Page = () => {
  return <Chats />;
};

export default Page;
