import Product from "@/components/dashboard/product";
import { BASE_URL, PAGES } from "@/constants/constants";
import { Metadata } from "next";

export const generateMetadata = ({
  params,
}: {
  params: { id: string };
}): Metadata => {
  return {
    // work on this
    title: "Pblafdkljroducts ~ Willow",
    description: "Generated by create next app", // Fix this
    openGraph: {
      title: "Products ~ Willow",
      description: "Generated by create next app", // Fix this
      type: "website",
      url: BASE_URL + PAGES.dashboard.products.product(params.id),
      images: [
        {
          url: "", // Fix this
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: "Products ~ Willow",
      description: "Generated by create next app",
      images: [
        {
          url: "", // Fix this
        },
      ],
    },
  };
};

const Page = ({ params }: { params: { id: string } }) => {
  console.log(params);

  return <Product />;
};

export default Page;
