import Shop from "@/components/general/shop";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { BASE_URL, IMAGES, PAGES } from "@/constants/constants";
import { Heart, Leaf, ShoppingBasket } from "lucide-react";
import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Shop ~ Willow",
  description: "Generated by create next app", // Fix this
  openGraph: {
    title: "Shop ~ Willow",
    description: "Generated by create next app", // Fix this
    type: "website",
    url: BASE_URL + PAGES.main.shop,
    images: [
      {
        url: "", // Fix this
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Shop ~ Willow",
    description: "Generated by create next app",
    images: [
      {
        url: "", // Fix this
      },
    ],
  },
};

const Page = () => {
  return <Shop />;
};

export default Page;
