"use client";

// import type { Metadata } from "next";
import "../globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { SiteHeader } from "@/components/dashboard/site-header";
import { AppSidebar } from "@/components/dashboard/app-sidebar";
import PageLoader from "@/components/general/page-loader";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { PAGES } from "@/constants/constants";
import { getJwtExpiration } from "@/lib/utils";

// export const metadata: Metadata = {
//   title: "Home ~ Willow",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      refetchInterval: 10000,
    },
  },
});

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  // useEffect(() => {
  //   const data = localStorage.getItem("willow_auth_data");

  //   if (!data) {
  //     router.push(PAGES.auth.login);
  //     return;
  //   }

  //   const { access_token } = JSON.parse(data);

  //   const date_ms = new Date().getTime();
  //   const expires_at = getJwtExpiration(access_token);

  //   if (!expires_at || date_ms >= expires_at) {
  //     localStorage.removeItem("willow_auth_data");
  //     router.push(PAGES.auth.login);
  //     return;
  //   }

  //   setLoading(false);
  // }, [router]);

  return (
    <QueryClientProvider client={queryClient}>
      <div className="w-full [--header-height:calc(theme(spacing.14))] bg-[#f5f5f5]">
        {loading ? (
          <PageLoader fullScreen />
        ) : (
          <SidebarProvider className="flex flex-col">
            <SiteHeader />
            <div className="flex flex-1 max-w-[1600px] p-4 bg-[#f5f5f5]">
              <AppSidebar />
              <SidebarInset className="flex flex-col gap-4 bg-[#f5f5f5]">
                {children}
              </SidebarInset>
            </div>
          </SidebarProvider>
        )}
      </div>
    </QueryClientProvider>
  );
};

export default RootLayout;
