"use client";

// import type { Metadata } from "next";
import "../globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { SiteHeader } from "@/components/dashboard/site-header";
import { AppSidebar } from "@/components/dashboard/app-sidebar";
import PageLoader from "@/components/general/page-loader";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { PAGES } from "@/constants/constants";

// export const metadata: Metadata = {
//   title: "Home ~ Willow",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      refetchInterval: 10000,
    },
  },
});

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const [loading, setLoading] = useState(true);
  const router = useRouter();

  useEffect(() => {
    const data = localStorage.getItem("willow_auth_data");

    if (!data) {
      router.push(PAGES.auth.login);
      return;
    }

    const { expires_at } = JSON.parse(data);
    const date_ms = new Date().getTime();

    if (date_ms >= expires_at) {
      localStorage.removeItem("willow_auth_data");
      router.push(PAGES.auth.login);
      return;
    }

    setLoading(false);
  }, [router]);

  return (
    <html lang="en">
      <body className="antialiased">
        <QueryClientProvider client={queryClient}>
          <div className="[--header-height:calc(theme(spacing.14))]">
            {loading ? (
              <PageLoader fullScreen />
            ) : (
              <SidebarProvider className="flex flex-col">
                <SiteHeader />
                <div className="flex flex-1 max-w-[1600px]">
                  <AppSidebar />
                  <SidebarInset>{children}</SidebarInset>
                </div>
              </SidebarProvider>
            )}
          </div>
        </QueryClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
